[project]
name = "my-aiops-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docx2txt>=0.9",
    "fastapi>=0.141.1",
    "fastmcp>=3.4.6",
    "langchain==1.2.10",
    "langchain-community>=0.4.2",
    "langchain-core>=1.5.3",
    "langchain-mcp-adapters>=0.3.2",
    "langchain-milvus==0.3.3",
    "langchain-ollama==1.0.1",
    "langchain-openai==1.1.9",
    "langchain-text-splitters>=1.1.2",
    "langfuse<4",
    "langgraph==1.0.8",
    "langgraph-checkpoint-postgres>=3.1.2",
    "langgraph-prebuilt==1.0.7",
    "loguru>=0.7.3",
    "openai>=2.53.0",
    "psycopg-binary>=3.3.4",
    "pymilvus==2.6.9",
    "pymupdf>=1.28.2",
    "rapidocr-onnxruntime>=1.4.4",
    "sse-starlette>=3.4.8",
    "tzdata>=2026.3",
    "uvicorn[standard]>=0.35,<0.36",
]
